### ISSUE TITLE
[HW1] JsonCrawler initializing

### ISSUE THREAD

**Issue by HyunyoungYoon** [swsnu/swppfall2017#18]
in __init__ method of JsonCrawler
I wonder what below code block does

`super(JsonCrawler, self).__init__()`

one more thing,
while initializing JasonCrawler instance I assigned the 'active' attribute like
`self.active = active`

but if I run the code it turns out to have an AttributeError like

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/hyunyoungyoon/developement/swppfall2017/hw1/python/crawler.py", line 37, in run
    del self.crawlers[self.name]
AttributeError: 'JsonCrawler' object has no attribute 'active'

**Comment by LastOne817** [comment]
1. `super(JsonCrawler, self).__init__()` is for initializing the parent class of `JsonCrawler` (For detailed information, check out https://stackoverflow.com/questions/3694371/how-do-i-initialize-the-base-super-class). You don't need to understand about class inheritance in this homework.
2. Check whether your added code is in the correct location of the skeleton code. `self.run` should be the very last line of the `__init__` method.

**Comment by LastOne817** [comment]
I've modified your question a bit in order to prevent spoiler. If you want to ask question regarding your implementation, please ask personally via email.
